import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { BLOG_POSTS, BlogPost } from './blog.data';

@Component({
  selector: 'app-blog', standalone: true,
  imports: [CommonModule, RouterLink],
  template: `
    <main class="blog-page mt-5 bg-white text-black lg:mt-7">
      <section class="blog-intro border-b border-black"><div class="mx-auto grid max-w-[1440px] gap-7 px-5 sm:px-8 lg:grid-cols-[1.2fr_.8fr] lg:items-end lg:px-14 xl:px-16"><div><p class="text-[9px] font-semibold tracking-[.22em]">M INCORPORATED BLOG</p><h1 class="mt-3 font-serif text-[54px] font-medium leading-[.9] tracking-[-.045em] sm:text-[66px] lg:text-[74px]">Lorem ipsum<br>dolor sit amet.</h1></div><p class="max-w-md text-[12px] leading-6 text-neutral-600 lg:mb-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p></div></section>
      <section class="featured-article mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-14 xl:px-16"><a [routerLink]="['/blog', posts[0].slug]" class="group grid overflow-hidden border border-black lg:grid-cols-[1.2fr_.8fr]"><div class="aspect-[4/3] overflow-hidden bg-neutral-100 lg:aspect-auto"><img [src]="posts[0].image" [alt]="posts[0].title" class="h-full w-full object-cover transition duration-500 group-hover:scale-[1.025]" /></div><div class="flex min-h-[390px] flex-col justify-between p-7 sm:p-9 lg:p-11"><div><p class="text-[8px] font-semibold tracking-[.18em]">FEATURED · {{ posts[0].category | uppercase }}</p><h2 class="mt-5 font-serif text-[38px] leading-[.94] tracking-[-.035em] sm:text-[46px]">{{ posts[0].title }}</h2><p class="mt-5 max-w-md text-[12px] leading-6 text-neutral-600">{{ posts[0].excerpt }}</p></div><div class="mt-8 flex items-center justify-between border-t border-black pt-4 text-[8px] font-semibold tracking-[.14em]"><span>{{ posts[0].date }}</span><span class="transition-transform duration-300 group-hover:translate-x-1">READ ARTICLE →</span></div></div></a></section>
      <section class="journal-index mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-14 xl:px-16"><div class="hide-scrollbar flex max-w-full gap-5 overflow-x-auto border-b border-black pb-4 text-[8px] font-semibold tracking-[.16em]">@for (category of categories; track category) {<button type="button" (click)="activeCategory = category" [class.border-b]="activeCategory === category" [class.border-black]="activeCategory === category" class="shrink-0 pb-1">{{ category | uppercase }}</button>}</div><div class="mt-7 flex items-center justify-between"><h2 class="font-serif text-[34px]">Latest articles</h2><span class="text-[8px] font-semibold tracking-[.16em]">{{ visiblePosts.length }} POSTS</span></div><div class="mt-6 grid gap-x-5 gap-y-14 md:grid-cols-2 lg:grid-cols-3">@for (post of visiblePosts; track post.slug) {<article><a [routerLink]="['/blog', post.slug]" class="group block"><div class="aspect-[4/3] overflow-hidden bg-neutral-100"><img [src]="post.image" [alt]="post.title" class="h-full w-full object-cover transition duration-500 group-hover:scale-[1.025]" /></div><p class="mt-4 text-[8px] font-semibold tracking-[.16em]">{{ post.category | uppercase }}</p><h3 class="mt-2 font-serif text-[30px] leading-[.95] tracking-[-.03em]">{{ post.title }}</h3><p class="mt-3 text-[11px] leading-5 text-neutral-600">{{ post.excerpt }}</p><div class="mt-4 flex justify-between text-[8px] font-semibold tracking-[.13em]"><span>{{ post.date }}</span><span class="transition-transform duration-300 group-hover:translate-x-1">READ →</span></div></a></article>}</div><div class="mt-14 text-center"><button type="button" class="border border-black px-5 py-4 text-[9px] font-semibold tracking-[.16em]">LOAD MORE ARTICLES →</button></div></section>
      <section class="blog-cta"><div class="mx-auto grid max-w-[1440px] gap-7 px-5 sm:px-8 lg:grid-cols-[1.2fr_.8fr] lg:items-end lg:px-14 xl:px-16"><div><p class="text-[9px] font-semibold tracking-[.2em]">M INCORPORATED</p><h2 class="mt-3 font-serif text-[42px] leading-[.94] sm:text-[54px]">Explore the people<br>behind the work.</h2></div><div class="flex flex-wrap gap-3 lg:justify-self-end"><a routerLink="/models" class="border border-black px-5 py-4 text-[9px] font-semibold tracking-[.16em]">VIEW MODELS →</a><a routerLink="/booking" class="bg-black px-5 py-4 text-[9px] font-semibold tracking-[.16em] text-white">START AN INQUIRY →</a></div></div></section>
    </main>
  `,
  styles: [`:host { display:block; background:#fff; color:var(--public-heading); } .blog-intro > div { padding-top:3.75rem; padding-bottom:4rem; } .featured-article { padding-top:3.5rem; } .journal-index { padding-top:4.5rem; padding-bottom:5rem; } .blog-cta { border-top:1px solid var(--public-heading); } .blog-cta > div { padding-top:4rem; padding-bottom:4rem; } .hide-scrollbar::-webkit-scrollbar { display:none; } .hide-scrollbar { scrollbar-width:none; } @media (max-width:640px) { .blog-intro > div { padding-top:3.5rem; padding-bottom:3.5rem; } .featured-article { padding-top:3rem; } .journal-index { padding-top:3.75rem; padding-bottom:4rem; } .blog-cta > div { padding-top:3.5rem; padding-bottom:3.5rem; } }`]
})
export class BlogComponent {
  readonly posts = BLOG_POSTS;
  readonly categories = ['All', 'Editorial', 'Talent', 'Bookings', 'Agency', 'Behind the Scenes'];
  activeCategory = 'All';
  get visiblePosts(): BlogPost[] { return this.posts.slice(1).filter((post) => this.activeCategory === 'All' || post.category === this.activeCategory); }
}
